# -*- coding: utf-8 -*-
"""
File: models/daily_report.py
Description: Daily Report Model - Auto-generated at End of Day
"""

from odoo import models, fields, api, _
from odoo.exceptions import UserError
from datetime import datetime, timedelta
import json
import logging

_logger = logging.getLogger(__name__)


class GasStationDailyReport(models.Model):
    _name = 'gas.station.daily.report'
    _description = 'Gas Station Daily Report'
    _inherit = ['mail.thread', 'mail.activity.mixin']
    _order = 'report_date desc, id desc'
    _rec_name = 'name'

    # =========================================================================
    # HEADER FIELDS
    # =========================================================================
    name = fields.Char(
        string='Reference',
        required=True,
        copy=False,
        readonly=True,
        default=lambda self: _('New'),
        index=True,
    )
    
    state = fields.Selection([
        ('draft', 'Draft'),
        ('confirmed', 'Confirmed'),
    ], string='Status', default='draft', readonly=True, tracking=True)
    
    report_date = fields.Date(
        string='Report Date',
        required=True,
        readonly=True,
        index=True,
        help="วันที่ของ Report (วันที่ทำ EOD)"
    )
    
    # Period
    period_start = fields.Datetime(
        string='Period Start',
        readonly=True,
        help="เวลาเริ่มต้น (EOD ก่อนหน้า)"
    )
    period_end = fields.Datetime(
        string='Period End',
        readonly=True,
        help="เวลาสิ้นสุด (EOD ปัจจุบัน)"
    )
    period_duration_hours = fields.Float(
        string='Duration (Hours)',
        compute='_compute_period_duration',
        store=True,
    )
    
    # Link to EOD Audit
    eod_audit_id = fields.Many2one(
        'gas.station.shift.audit',
        string='EOD Audit',
        readonly=True,
        domain=[('audit_type', '=', 'end_of_day')],
        help="Link to the End of Day audit that triggered this report"
    )
    previous_eod_audit_id = fields.Many2one(
        'gas.station.shift.audit',
        string='Previous EOD Audit',
        readonly=True,
        domain=[('audit_type', '=', 'end_of_day')],
    )
    
    # Company
    company_id = fields.Many2one(
        'res.company',
        string='Company',
        required=True,
        readonly=True,
        default=lambda self: self.env.company,
    )
    currency_id = fields.Many2one(
        'res.currency',
        string='Currency',
        required=True,
        readonly=True,
        default=lambda self: self.env.company.currency_id,
    )
    
    # Generated info
    generated_by = fields.Many2one(
        'res.users',
        string='Generated By',
        readonly=True,
        default=lambda self: self.env.user,
    )
    generated_at = fields.Datetime(
        string='Generated At',
        readonly=True,
        default=fields.Datetime.now,
    )
    
    # Notes
    notes = fields.Text(string='Notes')

    # =========================================================================
    # EXECUTIVE SUMMARY - KEY METRICS
    # =========================================================================
    
    # Total Revenue
    total_revenue = fields.Monetary(
        string='Total Revenue',
        currency_field='currency_id',
        readonly=True,
    )
    
    # Revenue by Category
    total_oil = fields.Monetary(
        string='Oil Sales',
        currency_field='currency_id',
        readonly=True,
    )
    total_engine_oil = fields.Monetary(
        string='Engine Oil Sales',
        currency_field='currency_id',
        readonly=True,
    )
    total_coffee_shop = fields.Monetary(
        string='Coffee Shop Sales',
        currency_field='currency_id',
        readonly=True,
    )
    total_convenient_store = fields.Monetary(
        string='Convenience Store Sales',
        currency_field='currency_id',
        readonly=True,
    )
    total_rental = fields.Monetary(
        string='Rental Income',
        currency_field='currency_id',
        readonly=True,
    )
    total_other = fields.Monetary(
        string='Other Income',
        currency_field='currency_id',
        readonly=True,
    )
    
    # Cash Flow
    total_deposits = fields.Monetary(
        string='Total Deposits',
        currency_field='currency_id',
        readonly=True,
        help="เงินฝากเข้าทั้งหมด"
    )
    total_withdrawals = fields.Monetary(
        string='Total Withdrawals',
        currency_field='currency_id',
        readonly=True,
        help="เงินถอนออกทั้งหมด"
    )
    net_cash_flow = fields.Monetary(
        string='Net Cash Flow',
        currency_field='currency_id',
        compute='_compute_net_cash_flow',
        store=True,
        help="เงินสดสุทธิ (Deposits - Withdrawals)"
    )
    
    # Replenish & Exchange (ไม่นับเป็น Revenue)
    total_deposit_cash = fields.Monetary(
        string='Replenish Cash',
        currency_field='currency_id',
        readonly=True,
        help="เงินเติมเข้าตู้"
    )
    total_exchange_cash = fields.Monetary(
        string='Exchange Cash',
        currency_field='currency_id',
        readonly=True,
        help="เงินแลก"
    )
    
    # Transaction Counts
    deposit_count = fields.Integer(
        string='Deposit Count',
        readonly=True,
    )
    withdrawal_count = fields.Integer(
        string='Withdrawal Count',
        readonly=True,
    )
    shift_count = fields.Integer(
        string='Shift Count',
        readonly=True,
        help="จำนวน shifts ใน period นี้"
    )
    
    # POS Summary
    pos_deposit_count = fields.Integer(
        string='POS Deposit Count',
        readonly=True,
    )
    pos_total_amount = fields.Monetary(
        string='POS Total Amount',
        currency_field='currency_id',
        readonly=True,
    )

    # =========================================================================
    # INVENTORY SNAPSHOT
    # =========================================================================
    
    # Opening Balance (ยอดเปิด - จาก EOD ก่อนหน้า หรือ reserve ที่เก็บไว้)
    opening_balance = fields.Monetary(
        string='Opening Balance',
        currency_field='currency_id',
        readonly=True,
        help="ยอดเงินสดในตู้ตอนเริ่มต้น period"
    )
    opening_inventory_json = fields.Text(
        string='Opening Inventory (JSON)',
        readonly=True,
        help="รายละเอียดธนบัตร/เหรียญ ตอนเปิด"
    )
    
    # Closing Balance (ยอดปิด - ก่อน collect ลง collection box)
    closing_balance = fields.Monetary(
        string='Closing Balance',
        currency_field='currency_id',
        readonly=True,
        help="ยอดเงินสดในตู้ก่อนเก็บลง Collection Box"
    )
    closing_inventory_json = fields.Text(
        string='Closing Inventory (JSON)',
        readonly=True,
        help="รายละเอียดธนบัตร/เหรียญ ก่อนเก็บ"
    )
    
    # Collection
    collected_amount = fields.Monetary(
        string='Collected Amount',
        currency_field='currency_id',
        readonly=True,
        help="จำนวนเงินที่เก็บลง Collection Box"
    )
    reserve_kept = fields.Monetary(
        string='Reserve Kept',
        currency_field='currency_id',
        readonly=True,
        help="เงินสำรองที่เก็บไว้ในตู้"
    )
    collection_breakdown_json = fields.Text(
        string='Collection Breakdown (JSON)',
        readonly=True,
    )
    
    # Inventory Summary (for display)
    total_notes = fields.Monetary(
        string='Total Notes',
        currency_field='currency_id',
        compute='_compute_inventory_summary',
        store=True,
    )
    total_coins = fields.Monetary(
        string='Total Coins',
        currency_field='currency_id',
        compute='_compute_inventory_summary',
        store=True,
    )

    # =========================================================================
    # RELATED RECORDS
    # =========================================================================
    
    shift_audit_ids = fields.Many2many(
        'gas.station.shift.audit',
        'daily_report_shift_audit_rel',
        'report_id',
        'audit_id',
        string='Shift Audits',
        readonly=True,
    )
    
    deposit_ids = fields.Many2many(
        'gas.station.cash.deposit',
        'daily_report_deposit_rel',
        'report_id',
        'deposit_id',
        string='Deposits',
        readonly=True,
    )
    
    withdrawal_ids = fields.Many2many(
        'gas.station.cash.withdrawal',
        'daily_report_withdrawal_rel',
        'report_id',
        'withdrawal_id',
        string='Withdrawals',
        readonly=True,
    )

    # =========================================================================
    # COMPUTED FIELDS
    # =========================================================================
    
    @api.depends('period_start', 'period_end')
    def _compute_period_duration(self):
        for record in self:
            if record.period_start and record.period_end:
                delta = record.period_end - record.period_start
                record.period_duration_hours = delta.total_seconds() / 3600
            else:
                record.period_duration_hours = 0
    
    @api.depends('total_deposits', 'total_withdrawals')
    def _compute_net_cash_flow(self):
        for record in self:
            record.net_cash_flow = (record.total_deposits or 0) - (record.total_withdrawals or 0)
    
    @api.depends('closing_inventory_json')
    def _compute_inventory_summary(self):
        for record in self:
            total_notes = 0
            total_coins = 0
            
            if record.closing_inventory_json:
                try:
                    inventory = json.loads(record.closing_inventory_json)
                    for item in inventory.get('notes', []):
                        total_notes += item.get('value', 0) * item.get('qty', 0)
                    for item in inventory.get('coins', []):
                        total_coins += item.get('value', 0) * item.get('qty', 0)
                except (json.JSONDecodeError, TypeError):
                    pass
            
            record.total_notes = total_notes
            record.total_coins = total_coins

    # =========================================================================
    # CRUD METHODS
    # =========================================================================
    
    def _generate_reference(self, report_date):
        """Generate reference: RPT-YYMMDD-XX"""
        date_str = report_date.strftime('%y%m%d')
        
        # Find existing reports on same date
        existing = self.search_count([
            ('report_date', '=', report_date),
        ])
        
        seq = str(existing + 1).zfill(2)
        return f"RPT-{date_str}{seq}"
    
    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if vals.get('name', _('New')) == _('New'):
                report_date = vals.get('report_date') or fields.Date.today()
                if isinstance(report_date, str):
                    report_date = fields.Date.from_string(report_date)
                vals['name'] = self._generate_reference(report_date)
        
        return super().create(vals_list)

    # =========================================================================
    # AUTO-GENERATE FROM EOD
    # =========================================================================
    
    @api.model
    def create_from_eod(self, eod_audit, inventory_before_collection=None):
        """
        Create Daily Report from End of Day audit.
        Called automatically when EOD is completed.
        
        Args:
            eod_audit: gas.station.shift.audit record (type=end_of_day)
            inventory_before_collection: dict from Glory API (optional)
            
        Returns:
            Created daily.report record
        """
        _logger.info("=" * 60)
        _logger.info("Creating Daily Report from EOD: %s", eod_audit.name)
        
        if eod_audit.audit_type != 'end_of_day':
            raise UserError(_("Can only create Daily Report from End of Day audit"))
        
        # Find previous EOD
        previous_eod = self.env['gas.station.shift.audit'].search([
            ('audit_type', '=', 'end_of_day'),
            ('close_time', '<', eod_audit.close_time),
            ('id', '!=', eod_audit.id),
        ], order='close_time desc', limit=1)
        
        # Determine period
        period_start = previous_eod.close_time if previous_eod else None
        period_end = eod_audit.close_time
        
        # Get all shifts in period
        shift_domain = [('id', '!=', eod_audit.id)]  # Exclude current EOD
        if period_start:
            shift_domain.append(('close_time', '>', period_start))
        shift_domain.append(('close_time', '<=', period_end))
        
        shifts = self.env['gas.station.shift.audit'].search(shift_domain)
        all_shifts = shifts | eod_audit  # Include EOD itself
        
        # Get all deposits in period
        deposit_domain = []
        if period_start:
            deposit_domain.append(('date', '>', period_start))
        deposit_domain.append(('date', '<=', period_end))
        
        deposits = self.env['gas.station.cash.deposit'].search(deposit_domain)
        
        # Get all withdrawals in period
        withdrawal_domain = []
        if period_start:
            withdrawal_domain.append(('date', '>', period_start))
        withdrawal_domain.append(('date', '<=', period_end))
        
        withdrawals = self.env['gas.station.cash.withdrawal'].search(withdrawal_domain)
        
        # Calculate totals by deposit type
        totals = self._calculate_deposit_totals(deposits)
        
        # Calculate withdrawal total
        total_withdrawals = sum(withdrawals.mapped('total_amount'))
        
        # POS deposits
        pos_deposits = deposits.filtered(lambda d: d.is_pos_related and d.pos_status == 'ok')
        
        # Opening balance (from previous EOD reserve or 0)
        opening_balance = previous_eod.reserve_kept if previous_eod else 0
        opening_inventory = None
        if previous_eod and previous_eod.collection_breakdown:
            # Previous EOD's reserve becomes opening
            try:
                opening_inventory = json.loads(previous_eod.collection_breakdown)
            except:
                pass
        
        # Prepare values
        vals = {
            'report_date': eod_audit.close_time.date(),
            'period_start': period_start,
            'period_end': period_end,
            'eod_audit_id': eod_audit.id,
            'previous_eod_audit_id': previous_eod.id if previous_eod else False,
            
            # Executive Summary
            'total_revenue': totals['revenue_total'],
            'total_oil': totals['oil'],
            'total_engine_oil': totals['engine_oil'],
            'total_coffee_shop': totals['coffee_shop'],
            'total_convenient_store': totals['convenient_store'],
            'total_rental': totals['rental'],
            'total_other': totals['other'],
            'total_deposit_cash': totals['deposit_cash'],
            'total_exchange_cash': totals['exchange_cash'],
            
            'total_deposits': totals['all_deposits'],
            'total_withdrawals': total_withdrawals,
            
            # Counts
            'deposit_count': len(deposits),
            'withdrawal_count': len(withdrawals),
            'shift_count': len(all_shifts),
            'pos_deposit_count': len(pos_deposits),
            'pos_total_amount': sum(pos_deposits.mapped('total_amount')),
            
            # Inventory
            'opening_balance': opening_balance,
            'opening_inventory_json': json.dumps(opening_inventory) if opening_inventory else False,
            'closing_balance': eod_audit.eod_grand_total or 0,
            'closing_inventory_json': json.dumps(inventory_before_collection) if inventory_before_collection else False,
            'collected_amount': eod_audit.collected_amount or 0,
            'reserve_kept': eod_audit.reserve_kept or 0,
            'collection_breakdown_json': eod_audit.collection_breakdown or False,
            
            # Relations
            'shift_audit_ids': [(6, 0, all_shifts.ids)],
            'deposit_ids': [(6, 0, deposits.ids)],
            'withdrawal_ids': [(6, 0, withdrawals.ids)],
        }
        
        report = self.create(vals)
        
        _logger.info("✅ Created Daily Report: %s", report.name)
        _logger.info("   Period: %s → %s", period_start, period_end)
        _logger.info("   Shifts: %d, Deposits: %d, Withdrawals: %d", 
                    len(all_shifts), len(deposits), len(withdrawals))
        _logger.info("=" * 60)
        
        return report
    
    def _calculate_deposit_totals(self, deposits):
        """Calculate totals by deposit type."""
        totals = {
            'oil': 0,
            'engine_oil': 0,
            'coffee_shop': 0,
            'convenient_store': 0,
            'rental': 0,
            'deposit_cash': 0,
            'exchange_cash': 0,
            'other': 0,
            'revenue_total': 0,
            'all_deposits': 0,
        }
        
        for deposit in deposits:
            amount = deposit.total_amount or 0
            totals['all_deposits'] += amount
            
            dtype = deposit.deposit_type
            if dtype == 'oil':
                totals['oil'] += amount
                totals['revenue_total'] += amount
            elif dtype == 'engine_oil':
                totals['engine_oil'] += amount
                totals['revenue_total'] += amount
            elif dtype == 'coffee_shop':
                totals['coffee_shop'] += amount
                totals['revenue_total'] += amount
            elif dtype == 'convenient_store':
                totals['convenient_store'] += amount
                totals['revenue_total'] += amount
            elif dtype == 'rental':
                totals['rental'] += amount
                totals['revenue_total'] += amount
            elif dtype == 'deposit_cash':
                totals['deposit_cash'] += amount
                # ไม่นับเป็น revenue
            elif dtype == 'exchange_cash':
                totals['exchange_cash'] += amount
                # ไม่นับเป็น revenue
            else:
                totals['other'] += amount
                totals['revenue_total'] += amount
        
        return totals

    # =========================================================================
    # ACTIONS
    # =========================================================================
    
    def action_confirm(self):
        """Confirm the report."""
        for record in self:
            record.state = 'confirmed'
    
    def action_draft(self):
        """Reset to draft."""
        for record in self:
            record.state = 'draft'
    
    def action_view_deposits(self):
        """Open deposits in this report."""
        self.ensure_one()
        return {
            'type': 'ir.actions.act_window',
            'name': _('Deposits'),
            'res_model': 'gas.station.cash.deposit',
            'view_mode': 'tree,form',
            'domain': [('id', 'in', self.deposit_ids.ids)],
            'context': {'create': False},
        }
    
    def action_view_withdrawals(self):
        """Open withdrawals in this report."""
        self.ensure_one()
        return {
            'type': 'ir.actions.act_window',
            'name': _('Withdrawals'),
            'res_model': 'gas.station.cash.withdrawal',
            'view_mode': 'tree,form',
            'domain': [('id', 'in', self.withdrawal_ids.ids)],
            'context': {'create': False},
        }
    
    def action_view_shifts(self):
        """Open shift audits in this report."""
        self.ensure_one()
        return {
            'type': 'ir.actions.act_window',
            'name': _('Shift Audits'),
            'res_model': 'gas.station.shift.audit',
            'view_mode': 'tree,form',
            'domain': [('id', 'in', self.shift_audit_ids.ids)],
            'context': {'create': False},
        }
    
    # =========================================================================
    # HELPER METHODS FOR VIEWS
    # =========================================================================
    
    def get_closing_inventory_display(self):
        """Get closing inventory for display in view."""
        self.ensure_one()
        result = {'notes': [], 'coins': [], 'total': 0}
        
        if self.closing_inventory_json:
            try:
                inventory = json.loads(self.closing_inventory_json)
                result['notes'] = inventory.get('notes', [])
                result['coins'] = inventory.get('coins', [])
                result['total'] = self.closing_balance
            except:
                pass
        
        return result
    
    def get_deposit_breakdown(self):
        """Get deposit breakdown by type for charts."""
        self.ensure_one()
        return [
            {'name': 'Oil Sales', 'value': self.total_oil or 0},
            {'name': 'Engine Oil', 'value': self.total_engine_oil or 0},
            {'name': 'Coffee Shop', 'value': self.total_coffee_shop or 0},
            {'name': 'Convenience Store', 'value': self.total_convenient_store or 0},
            {'name': 'Rental', 'value': self.total_rental or 0},
            {'name': 'Other', 'value': self.total_other or 0},
        ]